apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: store-demo
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001